# From: https://github.com/argenos/nldates-obsidian/blob/master/.github/workflows/release.yml -- largely changed
name: Build Sync version history plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: sync-version-history # Change this to the name of your plugin-id folder

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18.x' 
    - name: Build
      id: build
      run: | 
        npm install
        npm run build --if-present
        git config user.name "kometenstaub"
        git config user.email "83140328+kometenstaub@users.noreply.github.com"
        npx rexreplace "^.*?#(#+\s\[.*?\n.*?)(?=\s*#+\s\[)" "_" -s -M -G -m -o "CHANGELOG.md" > CHANGELOG-LATEST.md
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        
        gh release create "$tag"  \
          --title="$tag" \
          -F CHANGELOG-LATEST.md \
          build/main.js build/manifest.json build/styles.css